export const STORAGE_KEY = {
  'CHAT_GPT_WEB_TOKEN': 'CHAT_GPT_WEB_TOKEN',
  'CHAT_GPT_SECRET_API_KEY': 'CHAT_GPT_SECRET_API_KEY',
  'GITHUB_PERSONAL_ACCESS_TOKEN': 'GITHUB_PERSONAL_ACCESS_TOKEN',
  'CONVERSATION_ID': 'CONVERSATION_ID'
}