export const STORAGE_KEY = {
  'CHAT_GPT_WEB_TOKEN': 'CHAT_GPT_WEB_TOKEN',
  'CHAT_GPT_SECRET_API_KEY': 'CHAT_GPT_SECRET_API_KEY',
  'GITHUB_PERSONAL_ACCESS_TOKEN': 'GITHUB_PERSONAL_ACCESS_TOKEN',
  'CONVERSATION_ID': 'CONVERSATION_ID',
  'CHAT_BOT_STATUS': 'CHAT_BOT_STATUS'
}

export const MESSAGE_TYPE = {
  CHAT_GPT_POST_MSG: 'CHAT_GPT_POST_MSG',
  CHAT_GPT_RESPONDING: 'CHAT_GPT_RESPONDING',
  CHAT_GPT_RESPONSE: 'CHAT_GPT_RESPONSE',
  CHAT_GPT_CID: 'CHAT_GPT_CID'
}